name: roommates 
description: "RoomMate App for calculating and dividing monthly expenses fairly."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  path_provider: ^2.0.0
  intl: ^0.20.2
  cupertino_icons: ^1.0.8
  sqflite: ^2.4.2
  flutter_native_splash: ^2.4.6
  flutter_launcher_icons: ^0.14.3
  fl_chart: ^0.64.0
  path: ^1.9.1
  pdf: ^3.10.4
  printing: ^5.11.0
  font_awesome_flutter: ^10.8.0
  smooth_page_indicator: ^1.2.1
  url_launcher: ^6.2.5
  shared_preferences: ^2.5.3
  flutter_local_notifications: ^19.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/logo/
    - assets/images/

  fonts:
    - family: main
      fonts:
        - asset: fonts/BebasNeue-Regular.ttf
    - family: myfont
      fonts:
        - asset: fonts/AlfaSlabOne-Regular.ttf

  

flutter_native_splash:
  color: '#ffb800'
  image: assets/logo/logo.jpg
  branding: assets/logo/branding.png

  android_12:
    color: '#ffb800'  
    image: assets/logo/splash_logo.png
    branding: assets/logo/branding.png
    android_gravity: center
  
  android: true
  ios: true

flutter_launcher_icons:
  android: true
  ios: true
  image_path: assets/logo/logo.jpg
